travis:
  secure:
    BINSTAR_TOKEN: fXggtw5vII+DG81b6Huz1Sg+k7UQPdwoP0MSnMqyrmz0yYYQRaCda/jORS6jJjVOysIiB40i7k+0v0K8/V1LbXmkiYxhuWEmd8P2lXkaXXNJSUDmk44ouf35XkvH90VlHnXDkW60gXtm6q92Y4I4QVtCIdpyD/UE/5wsjAODav4C83WtAKQmAKS92sptMTv30N9oC8ydmsSR1dKFDtWHACrRId8+pCZPHupZp5LqIHTAqqJ6cEgtrrM36bC26XhGyzH22BgCv98NZEOx3JyEtBczJz1JyZYxKkjJlXd1qXn0Z0Ab5pjJmdtuYmyDAx7gUTSm0HjM2sJtgud1ikPSCQY8nAhU8fqHP1liOEZDgesU3c20rXTi5wfyVZb805f8ybp1Hf7hkIWRU1Kvp2lFlogOpEogYwfe6iAj7dCDsQFzH8yNZXTSrzQRfkIva75Cmx0Iu24zk1eqediT1SRpY0oaUe3H7LN59eF9TuGFz01jJBdsD5uNwLXfapmL2lp+Gg4Zgu9bXXSEL1pBqynnHuwJVnhdBPjKHAfgaYDTIJtC615QAi25JcxDY7xi2wLEFPHuLaYzvtDeGuOi01RwXzhl1qy3xMOsQIpKLh9UFgdQK8+7eJ5AApGLedIX+LCRSyWLS3895lYQOE7z5tdxT9bcaPbPSPzNFJiGyuXYOcw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
